// <auto-generated />
namespace testwebapplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ContextDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContextDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201701030430549_-ContextDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
